/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.view;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author HP
 */
public class NewTransactionFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewTransactionFrame
     */
    public NewTransactionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtaccno = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        cmbTrans = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Lblout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setText("Account No.");

        jLabel6.setText("Enter the details");

        jLabel2.setText("Ammount");

        txtaccno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccnoActionPerformed(evt);
            }
        });

        cmbTrans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit", "Debit", " " }));

        jLabel3.setText("Type of Transaction");

        Lblout.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTrans, 0, 71, Short.MAX_VALUE)
                            .addComponent(txtamount)
                            .addComponent(txtaccno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lblout, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnSubmit)
                .addGap(18, 18, 18)
                .addComponent(Lblout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaccnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccnoActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        // TODO add your handling code here:
        int accno=Integer.parseInt(txtaccno.getText().trim());
        BigDecimal ammount=new BigDecimal(txtamount.getText().trim());
        
        String transtype=(String) cmbTrans.getSelectedItem();
        if("Credit".equals(transtype))
        {
            	
		try {
			
			// load and establish conncetion to JDBC driver
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_banking","root","root");  
			
			//load balance ammount before actual transaction 
			Statement stmt=con.createStatement();
			
			//query to get total_balance from tbl_account
			String getBalance = "select total_balance from db_banking.tbl_account where account_number="+accno;
			ResultSet rs = stmt.executeQuery( getBalance);
			BigDecimal totalBalance=null;
			while(rs.next())
				totalBalance= rs.getBigDecimal("total_balance");
			
			//will add amount deposited now in total_balance of customer
			totalBalance= totalBalance.add(ammount);
			String creditTransactionQuery = "INSERT INTO `db_banking`.`tbl_transaction` (`account_number`, `transactionDate`,`ammount`, `transaction_Type`, `balance`) VALUES (?, ?, ?, ?, ?)";
			// will add row in Transaction table of given account number
			PreparedStatement preparedStmt2 = con.prepareStatement(creditTransactionQuery);
			preparedStmt2.setInt (1, accno);
			preparedStmt2.setDate(2, NewTransactionFrame.getCurrentDate());
			preparedStmt2.setBigDecimal (3, ammount);
			preparedStmt2.setString   (4, "CR");
			preparedStmt2.setBigDecimal (5, totalBalance);
			preparedStmt2.execute();
			Lblout.setText("Credit transaction");
			
			//will update total amount after credit operation
			String updateBalance= "UPDATE `db_banking`.`tbl_account` SET `total_Balance`="+totalBalance+" WHERE `account_number`="+accno;	
			PreparedStatement preparedStmt = con.prepareStatement(updateBalance);
			Lblout.setText("balance updated");
			preparedStmt.execute();
		      
		}catch(Exception e) {
			System.out.println(e);	//raise the exception if  any
		}
                
		
        }
        else{
              	try {

			// load and establish conncetion to JDBC driver
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_banking","root","root");  
			
			//load balance ammount before actual transaction 
			Statement stmt=con.createStatement();
			
			//query to get total_balance from tbl_account
			String getBalance = "select total_balance from db_banking.tbl_account where account_number="+accno;
			ResultSet rs = stmt.executeQuery( getBalance);
			
			BigDecimal totalBalance=null;
			while(rs.next())
				totalBalance= rs.getBigDecimal("total_balance");
			
			//check balance is less than ammount entered by user
			int i = totalBalance.compareTo(ammount);
			if(i>=0) {
				//If less then withdraw operation executed here
				totalBalance= totalBalance.subtract(ammount);
				
                                String creditTransactionQuery = "INSERT INTO `db_banking`.`tbl_transaction` (`account_number`, `transactionDate`,`ammount`, `transaction_Type`, `balance`) VALUES (?, ?, ?, ?, ?)";
				// will create record of withdraw in transaction table
				PreparedStatement preparedStmt2 = con.prepareStatement(creditTransactionQuery);
				preparedStmt2.setInt (1, accno);
				preparedStmt2.setDate(2, NewTransactionFrame.getCurrentDate());
				preparedStmt2.setBigDecimal (3, ammount);
				preparedStmt2.setString   (4, "DB");
				preparedStmt2.setBigDecimal (5, totalBalance);
				preparedStmt2.execute();
				System.out.println("Debit transaction");
				
				//Update balance in account after withdraw
				String updateBalance= "UPDATE `db_banking`.`tbl_account` SET `total_Balance`="+totalBalance+" WHERE `account_number`="+accno;	
				PreparedStatement preparedStmt = con.prepareStatement(updateBalance);
				
				//print total balance
				Lblout.setText("balance updated");
				preparedStmt.execute();
			}else {
				//if ammount is more the balance in account then give Error of low balance
				Lblout.setText("LOW AMMOUNT");
			}
			
		      
		}catch(ClassNotFoundException | SQLException e) {
			System.out.println(e); //raise the exception if  any
		}
            
        }
    }//GEN-LAST:event_btnSubmitActionPerformed
private static java.sql.Date getCurrentDate() {
		//to load currunt time in date 
	    java.util.Date today = new java.util.Date();
	    return new java.sql.Date(today.getTime());
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTransactionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lblout;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbTrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtaccno;
    private javax.swing.JTextField txtamount;
    // End of variables declaration//GEN-END:variables
}
